_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: False
  META_ARCHITECTURE: "VGT"
  WORDGRID:
    VOCAB_SIZE: 250005
    EMBEDDING_DIM: 64
    MODEL_PATH: "./xlm-roberta-uncased/"
    USE_PRETRAIN_WEIGHT: True
  PIXEL_MEAN: [ 127.5, 127.5, 127.5 ]
  PIXEL_STD: [ 127.5, 127.5, 127.5 ]
  BACKBONE:
    NAME: "build_VGT_fpn_backbone"
  WEIGHTS: "/content/drive/MyDrive/github/vision-grid-transformer/dit-base-224-p16-500k-62d53a.pth"
  VIT:
    NAME: "VGT_dit_base_patch16"
    MERGE_TYPE: "Sum"
  ROI_HEADS:
    NAME: CascadeROIHeads
    NUM_CLASSES: 5
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
SOLVER:
  BASE_LR: 0.0005
  WARMUP_ITERS: 5
  STEPS: (10, 20)
  MAX_ITER: 15
  IMS_PER_BATCH: 3
TEST:
  EVAL_PERIOD: 5
DATASETS:
  TRAIN: ("publaynet_train",)
  TEST: ("publaynet_val",)